projetoweb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('usuarios.urls', namespace='usuarios', app_name='usuarios')),
]

usuarios/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^AreaLogada$', views.area_logada, name='area_logada'),
    url(r'^sobre$', views.sobre, name='sobre'),
    url(r'^login$', views.entrar, name='login'),
    url(r'^logout$', views.sair, name='logout'),
    url(r'^cadastro_sucesso$', views.cadastro_sucesso, name='cadastro_sucesso')
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User

class User(models.Model):
   username = models.CharField(max_length = 40)
   first_name = models.CharField(max_length = 40)
   last_name= models.CharField(max_length = 40)
   email = models.CharField(max_length = 100)
   password = models.CharField(max_length = 10)

   def __str__(self):
      return self.username

usuarios/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm, Form
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

class UserModelForm(forms.ModelForm):
    User._meta.get_field('username').blank = False
    User._meta.get_field('first_name').blank = False
    User._meta.get_field('last_name').blank = False
    User._meta.get_field('email').blank = False
    User._meta.get_field('password').blank = False
    class Meta:
        model = User
        fields = ['username', 'first_name','last_name', 'email', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control', 'maxlength': 30, 'placeholder':'Username'}),
            'first_name': forms.TextInput(attrs={'class':'form-control', 'maxlength': 30, 'placeholder':'Primeiro nome'}),
            'last_name': forms.TextInput(attrs={'class':'form-control', 'maxlength': 30, 'placeholder':'Sobrenome'}),
            'email': forms.TextInput(attrs={'class':'form-control', 'maxlength': 30, 'placeholder':'Email'}),
            'password': forms.PasswordInput(attrs={'class':'form-control', 'maxlength': 30, 'placeholder':'Senha'}),
        }

        error_messages = {
            'username':{
                'required':'Este campo é obrigatório'
            },
            'first_name':{
                'required':'Este campo é obrigatório'
            },
            'last_name':{
                'required':'Este campo é obrigatório'
            },
            'email':{
                'required':'Escreva um email válido'
            },
            'password':{
                'required':'Este campo é obrigatório'
            }
        }

    def save(self, commit=True):
        user = super(UserModelForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

class LoginForm(forms.Form):
    username = forms.CharField(max_length=255, required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if not user or not user.is_active:
            raise forms.ValidationError("Usuário e/ou senha incorretos! Por favor, tente novamente!")
        return self.cleaned_data

    def login(self, request):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        return user

usuarios/views.py
from django.shortcuts import render, redirect, render_to_response
from django.http import HttpResponseRedirect
from usuarios.forms import UserModelForm, LoginForm
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.template import RequestContext
from django.contrib import messages


def home(request):
    form = UserModelForm(request.POST or None)
    context = {'form':form}
    if request.method == 'POST':
        
        if form.is_valid():
            try:
                form.save()
                return redirect('/cadastro_sucesso')
            except IntegrityError:
                messages.info(request, 'Usuário e/ou Email já cadastrados.  Por favor, tente novamente!')
                return render_to_response('usuarios/index.html', locals(), context_instance=RequestContext(request))
          
    
    return render(request, 'usuarios/index.html', context)


@login_required
def area_logada(request):
   return render(request, 'usuarios/AreaLogada.html', {})


def entrar(request):
    form = LoginForm(request.POST or None)
    if request.POST and form.is_valid():
        user = form.login(request)
        if user:
            login(request, user)
            return HttpResponseRedirect("/AreaLogada")# Redirect to a success page.
    return render(request, 'usuarios/login.html', {'form': form })


@login_required
def sair(request):
    logout(request)
    return HttpResponseRedirect('/login')


def cadastro_sucesso(request):
   return render(request, 'usuarios/cadastro_sucesso.html', {})


def sobre(request):
   return render(request, 'usuarios/sobre.html', {})

usuarios/templates/usuarios/AreaLogada.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>text Messenger</title>
    <link rel="shortcut icon" href="{% static 'img/_logo.png' %}" width="16" height="13"> 
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="{% static 'js/validator.min.js' %}"></script>
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href="{% static 'css/style_areaLogada.css' %}" rel="stylesheet">
</head>
	<body>
	<!-- Navigation -->
	<nav class="navbar navbar-expand-md navbar-light sticky-top">
		<div class="container-fluid">
			<a class="navbar-brand" href="AreaLogada"><img src="{% static 'img/logotext.png' %}" width="162" height="53"></a>
			<div class="collapse navbar-collapse" id="navbarResponsive">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item">
						<a class="mr-sm-4"></a>
						<button OnClick="logout()" class="btn btn-success my-2 my-sm-0" type="submit">Sair</button>
					</li>
				</ul>
			</div>
		</div>
	</nav>
	<!--- Home -->
	<div id="home">
		<div class="w3-sidebar w3-bar-block w3-white" style="width:80px">
		<br> <br> <br> <br>
		<a OnClick="whatsapp()" class="w3-bar-item w3-button" style="font-size: 30px"><img src="{% static 'img/icons/WhatsApp_icon.png' %}"></a><br><br>
		<a OnClick="slack()" class="w3-bar-item w3-button" style="font-size: 30px"><img src="{% static 'img/icons/slack_icon.png' %}"></a><br><br>
		<a OnClick="telegram()" class="w3-bar-item w3-button" style="font-size: 30px"><img src="{% static 'img/icons/telegram_icon.png' %}"></a><br><br>
		<a OnClick="messenger()" class="w3-bar-item w3-button" style="font-size: 30px"><img src="{% static 'img/icons/Messenger_icon.png' %}"></a>
		</div>          
	</div>
		<script>
			function whatsapp() {
				window.open("https://web.whatsapp.com", "_blank", 	
				"toolbar=yes,scrollbars=yes,resizable=yes,top=0,left=500,width=1000,height=1000");
			}
			function slack() {
				window.open("https://slack.com/signin", "_blank", 	
				"toolbar=yes,scrollbars=yes,resizable=yes,top=0,left=500,width=1000,height=1000");
			}
			function telegram() {
				window.open("https://web.telegram.org", "_blank", 	
				"toolbar=yes,scrollbars=yes,resizable=yes,top=0,left=500,width=1000,height=1000");
			}
			function messenger() {
				window.open("https://www.messenger.com", "_blank", 	
				"toolbar=yes,scrollbars=yes,resizable=yes,top=0,left=500,width=1000,height=1000");
			}
			function logout() {
                window.location.href = 'logout';
            }
		</script>
	</body>
</html>

usuarios/templates/usuarios/cadastro_sucesso.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>text Messenger</title>
    	<link rel="shortcut icon" href="{% static 'img/_logo.png' %}" width="16" height="13"> 
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
        <script src="{% static 'js/validator.min.js' %}"></script>
    	<script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    	<link rel="stylesheet" href="{% static 'css/w3.css' %}">
    	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href="{% static 'css/style_login.css' %}" rel="stylesheet">
</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light sticky-top">
	<div class="container-fluid">
		<a class="navbar-brand" href="#"><img src="{% static 'img/logotext.png' %}" width="162" height="53"></a>
	</div>
</nav>
<!--- Home -->
<div id="home">
    <div class="modal-dialog text-center">
        <div class="col-sm-9 main-section"> 
            <div class="modal-content">
                <div class="col-sm-12">
                    <h4 class="h3-singup">Parabéns: Seu cadastro foi realizado com sucesso.</h4>
                    <h4 class="h3-singup">Faça seu login.</h4>
                    <div>
                        <button onclick="login();" class="btn btn-success bnt-block">Login</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    
<!--- Footer -->
<footer class="container-fluid text-center">
    <div class="socialicon" class="col">
        <a href="https://www.facebook.com" ><img class="fab fa-facebook"></a>
        <a href="https://www.twitter.com" ><img class="fab fa-twitter"></a>
        <a href="https://www.googleplus.com" ><img class="fab fa-google"></a>
        <a href="https://www.instagram.com" ><img class="fab fa-instagram"></a>
        <a href="https://github.com" ><img class="fab fa-github"></a>
    </div>
    <p>&copy Copyright 2018 by text - All Rights Reserved  :p </p>
</footer>
<script>
    function login() {
                window.location.href = 'login';
            }
</script>
</body>
</html>

usuarios/templates/usuarios/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>text Messenger</title>
    <link rel="shortcut icon" href="{% static 'img/_logo.png' %}" width="16" height="13"> 
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="{% static 'js/validator.min.js' %}"></script>
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
	<link type=text/css  href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light sticky-top">
	<div class="container-fluid">
		<a class="navbar-brand" href=""><img src="{% static 'img/logotext.png' %}" width="162" height="53"></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ml-auto">
                <li class="nav-item">
				    <a class="nav-link mr-sm-4" href="sobre">Sobre</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link mr-sm-4" href="login">Login</a>
                </li>
			</ul>  
		</div>
        
	</div>
</nav>
<!--- Home -->
<div id="home">
    <div class="modal-dialog text-center">
        <div class="col-sm-9 main-section"> 
            <div class="modal-content">
                <div class="col-sm-12">
                    <h4 class="h3-singup">Crie sua conta</h4>
                    {% block content %}
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                    <form action="{% url 'usuarios:home' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.username}}
                            {{form.username.errors}} 
                        </div>
                        <div class="form-group">
                            {{ form.first_name}}
                            {{form.first_name.errors}} 
                        </div>
                        <div class="form-group">
                            {{ form.last_name}}
                            {{form.last_name.errors}}
                        </div>
                        <div class="form-group">
                            {{ form.email}}
                            {{form.email.errors}}
                        </div>
                        <div class="form-group">
                            {{ form.password}}
                            {{form.password.errors}}
                        </div>
                        <div>
                            <button type="submit" class="btn btn-success bnt-block">Criar Conta</button>
                        </div>
                    </form>
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
</div>
<!--- Footer -->
<footer class="container-fluid text-center">
    <div class="socialicon" class="col">
        <a href="https://www.facebook.com" ><img class="fab fa-facebook"></a>
        <a href="https://www.twitter.com" ><img class="fab fa-twitter"></a>
        <a href="https://www.googleplus.com" ><img class="fab fa-google"></a>
        <a href="https://www.instagram.com" ><img class="fab fa-instagram"></a>
        <a href="https://github.com" ><img class="fab fa-github"></a>
    </div>
    <p>&copy Copyright 2018 by text - All Rights Reserved  :p </p>
</footer>
</body>
</html>

usuarios/templates/usuarios/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>text Messenger</title>
    <link rel="shortcut icon" href="{% static 'img/_logo.png' %}" width="16" height="13"> 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="{% static 'js/validator.min.js' %}"></script>
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <link type=text/css  href="{% static 'css/style_login.css' %}" rel="stylesheet">
    </head>
    <body>
<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light sticky-top">
	<div class="container-fluid">
		<a class="navbar-brand" href="/"><img src="{% static 'img/logotext.png' %}" width="162" height="53"></a>
		<div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item">
					<button onclick="home();" class="btn btn-success bnt-block">Voltar para home</button>
				</li>
			</ul>
		</div>
	</div>
</nav>

<script>
    function home() {
                window.location.href = '/';
            }
</script>

<!--- Home -->
<div id="home">
    <div class="modal-dialog text-center">
        <div class="col-sm-9 main-section"> 
            <div class="modal-content">
                <div class="col-sm-12">
                    <h4 class="h3-singup">Faça seu Login</h4>
                    {% block content %}
                    {% if form.non_field_errors %}
                        <ul class='form-errors'>
                            {% for error in form.non_field_errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}    
                    <form action="{% url 'usuarios:login' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="text" name="username" class="form-control" placeholder="Username" required="required"\>
                        </div>
                        <div class="form-group">
                            <input type="password" name="password" class="form-control" placeholder="Senha" required="required"\>
                        </div>

                        <div>
                            <button type="submit" class="btn btn-success bnt-block">Login</button>
                        </div>
                    </form>
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
</div>
    
<!--- Footer -->
<footer class="container-fluid text-center">
    <div class="socialicon" class="col">
        <a href="https://www.facebook.com" ><img class="fab fa-facebook"></a>
        <a href="https://www.twitter.com" ><img class="fab fa-twitter"></a>
        <a href="https://www.googleplus.com" ><img class="fab fa-google"></a>
        <a href="https://www.instagram.com" ><img class="fab fa-instagram"></a>
        <a href="https://github.com" ><img class="fab fa-github"></a>
    </div>
    <p>&copy Copyright 2018 by text - All Rights Reserved  :p </p>
</footer>

</body>
</html>

usuarios/templates/usuarios/sobre.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>text Messenger</title>
	<link rel="shortcut icon" href="{% static 'img/_logo.png' %}" width="16" height="13"> 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="{% static 'js/validator.min.js' %}"></script>
	<script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href="{% static 'css/style_login.css' %}" rel="stylesheet">
</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light sticky-top">
	<div class="container-fluid">
		<a class="navbar-brand" href="#"><img src="{% static 'img/logotext.png' %}" width="162" height="53"></a>
	</div>
</nav>
<!--- Home -->
<div id="home">
    <div class="modal-dialog text-center">
        <div class="col-sm-10 main-section"> 
            <div class="modal-content">
                <div class="col-sm-15">
                    <h4>O Text é um serviço que conecta os seus principais aplicativos de mensagens em um único lugar.</h4> 
                    <h4>Você pode utilizar o Whatsapp, Slack, Messenger, e Telagram em um só site.</h4><br>
                    <img src="{% static 'img/_logo.png' %}" width="22%" />
                    <a> = </a>
                    <img src="{% static 'img/WhatsApp_icon.png' %}" width="10%" /> <a> + </a>
                    <img src="{% static 'img/slack_icon.png' %}" width="10%" /> <a> + </a>
                    <img src="{% static 'img/telegram_icon.png' %}" width="10%" /> <a> + </a>
                    <img src="{% static 'img/Messenger_icon.png' %}" width="10%" />
                </div>
                <div>
                    <button onclick="home();" class="btn btn-success bnt-block">Voltar para home</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    function home() {
                window.location.href = '/';
            }
</script>
<!--- Footer -->
<footer class="container-fluid text-center">
    <div class="socialicon" class="col">
        <a href="https://www.facebook.com" ><img class="fab fa-facebook"></a>
        <a href="https://www.twitter.com" ><img class="fab fa-twitter"></a>
        <a href="https://www.googleplus.com" ><img class="fab fa-google"></a>
        <a href="https://www.instagram.com" ><img class="fab fa-instagram"></a>
        <a href="https://github.com" ><img class="fab fa-github"></a>
    </div>
    <p>&copy Copyright 2018 by text - All Rights Reserved  :p </p>
</footer>
</body>
</html>